<a href="https://colab.research.google.com/github/Ivanov85/Homework1/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd

In [27]:
user_table = pd.read_csv("/content/user_table.csv")
user_table

       user_id        date   device     sex
0       450007  2015-02-28  Desktop  Female
1       756838  2015-01-13  Desktop    Male
2       568983  2015-04-09  Desktop    Male
3       190794  2015-02-18  Desktop  Female
4       537909  2015-01-15  Desktop    Male
...        ...         ...      ...     ...
90395   307667  2015-03-30  Desktop  Female
90396   642989  2015-02-08  Desktop  Female
90397   659645  2015-04-13  Desktop    Male
90398   359779  2015-03-23  Desktop    Male
90399   438929  2015-03-26   Mobile  Female

[90400 rows x 4 columns]

In [28]:
user_table.shape

(90400, 4)

In [29]:
home_page = pd.read_csv("/content/home_page_table.csv")
home_page.head()

   user_id       page
0   313593  home_page
1   468315  home_page
2   264005  home_page
3   290784  home_page
4   639104  home_page

In [30]:
home_page.shape

(90400, 2)

In [31]:
sum(home_page.duplicated())

0

In [32]:
search_page = pd.read_csv("/content/search_page_table.csv")
search_page.head()

   user_id         page
0    15866  search_page
1   347058  search_page
2   577020  search_page
3   780347  search_page
4   383739  search_page

In [33]:
search_page.shape

(45200, 2)

In [34]:
payment_page = pd.read_csv("/content/payment_page_table.csv")
payment_page.head()

   user_id          page
0   253019  payment_page
1   310478  payment_page
2   304081  payment_page
3   901286  payment_page
4   195052  payment_page

In [35]:
payment_page.shape

(6030, 2)

In [36]:
payment_confirmation = pd.read_csv("/content/payment_confirmation_table.csv")
payment_confirmation.head()

   user_id                       page
0   123100  payment_confirmation_page
1   704999  payment_confirmation_page
2   407188  payment_confirmation_page
3   538348  payment_confirmation_page
4   841681  payment_confirmation_page

In [37]:
payment_confirmation.shape

(452, 2)

In [38]:
home_page = home_page.rename(columns = {"page": "home_page"})
search_page = search_page.rename(columns = {"page": "search_page"})
payment_page = payment_page.rename(columns = {"page": "payment_page"})
payment_confirmation = payment_confirmation.rename(columns = {"page": "payment_confirmation"})

In [39]:
df = user_table.merge(home_page, on = "user_id", how = "left").merge(search_page, on = "user_id", how = "left")\
        .merge(payment_page, on = "user_id", how = "left").merge(payment_confirmation, on = "user_id", how = "left")
df.head()

,user_id,date,device,sex,home_page,search_page,payment_page,payment_confirmation
0,450007,2015-02-28,Desktop,Female,home_page,NaN,NaN,NaN
1,756838,2015-01-13,Desktop,Male,home_page,NaN,NaN,NaN
2,568983,2015-04-09,Desktop,Male,home_page,search_page,NaN,NaN
3,190794,2015-02-18,Desktop,Female,home_page,search_page,NaN,NaN
4,537909,2015-01-15,Desktop,Male,home_page,NaN,NaN,NaN

In [40]:
df.shape

(90400, 8)

In [41]:
df["home_page"] = df["home_page"].apply(lambda x: 1 if x == "home_page" else 0)
df["search_page"] = df["search_page"].apply(lambda x: 1 if x == "search_page" else 0)
df["payment_page"] = df["payment_page"].apply(lambda x: 1 if x == "payment_page" else 0)
df["payment_confirmation"] = df["payment_confirmation"].apply(lambda x: 1 if x == "payment_confirmation_page" else 0)

df.head()

,user_id,date,device,sex,home_page,search_page,payment_page,payment_confirmation
0,450007,2015-02-28,Desktop,Female,1,0,0,0
1,756838,2015-01-13,Desktop,Male,1,0,0,0
2,568983,2015-04-09,Desktop,Male,1,1,0,0
3,190794,2015-02-18,Desktop,Female,1,1,0,0
4,537909,2015-01-15,Desktop,Male,1,0,0,0

In [42]:
df["device"].value_counts()

Desktop    60200
Mobile     30200
Name: device, dtype: int64

In [43]:
df["payment_confirmation"].agg({"users": "count", "payers": sum})

users     90400
payers      452
Name: payment_confirmation, dtype: int64

In [44]:
summary = df[["home_page", "search_page", "payment_page", "payment_confirmation"]].sum().reset_index()
summary.head()

                  index      0
0             home_page  90400
1           search_page  45200
2          payment_page   6030
3  payment_confirmation    452

In [45]:
summary = summary.rename(columns = {"index" : "stage", 0: "number"})
summary.head()

                  stage  number
0             home_page   90400
1           search_page   45200
2          payment_page    6030
3  payment_confirmation     452

In [46]:
from plotly import graph_objects as go

fig = go.Figure(go.Funnel(
    y = summary["stage"],
    x = summary["number"],
    textinfo = "value + percent previous"
))

fig.update_layout(
    title = "Воронка конверсии Интернет-магазина",
    title_x = 0.5,
    autosize = False,
    width = 1200,
    height = 600

)

fig.show()

In [47]:
dfg = df.groupby("device")[["home_page", "search_page", "payment_page", "payment_confirmation"]].sum().unstack("device").unstack("device").reset_index()

dfg.columns.name = None
dfg = dfg.rename(columns = {"index": "Page"})
dfg.head()

                   Page  Desktop  Mobile
0             home_page    60200   30200
1           search_page    30100   15100
2          payment_page     3010    3020
3  payment_confirmation      150     302

In [51]:
fig = go.Figure(go.Funnel(
    y = dfg ["Page"],
    x = dfg ["Desktop"],
    textinfo = "value + percent previous",
    name = "Desktop",
    constraintext = "outside",
    textposition = "inside"
))

fig.add_trace(go.Funnel(
    y = dfg ["Page"],
    x = dfg ["Mobile"],
    textinfo = "value + percent previous",
    name = "Mobile",
    constraintext = "outside",
    textposition = "inside"
))

fig.update_layout(
    title = "Воронка конверсии по типам устройств",
    title_x = 0.5,
    autosize = False,
    width = 1200,
    height = 600

)

fig.show()

In [57]:
pd.pivot_table(df, index = "sex", columns = "device", values = "home_page", aggfunc = "sum", margins = True)

device  Desktop  Mobile    All
sex
Female    29997   15078  45075
Male      30203   15122  45325
All       60200   30200  90400

In [59]:
pd.crosstab(index = df["sex"], columns = df["device"], margins = True, normalize = True)

device   Desktop    Mobile       All
sex
Female  0.331825  0.166792  0.498617
Male    0.334104  0.167279  0.501383
All     0.665929  0.334071  1.000000

In [60]:
df.groupby(["sex", "device"])["user_id"].count().reset_index()

      sex   device  user_id
0  Female  Desktop    29997
1  Female   Mobile    15078
2    Male  Desktop    30203
3    Male   Mobile    15122

In [61]:
df.groupby(["sex", "device"])["user_id"].count().unstack("device")

device  Desktop  Mobile
sex
Female    29997   15078
Male      30203   15122

In [62]:
from pandas.core.groupby import groupby
(df.groupby("sex")["search_page"].sum() - df.groupby("sex")["payment_page"].sum())/df.groupby("sex")["search_page"].sum()

sex
Female    0.863292
Male      0.869917
dtype: float64

In [63]:
pd.crosstab(index= df["sex"], columns= df["payment_confirmation"], normalize= True)

payment_confirmation         0         1
sex
Female                0.495951  0.002666
Male                  0.499049  0.002334

In [64]:
df.pivot_table(index = ["sex"], values = "payment_confirmation")

        payment_confirmation
sex
Female              0.005347
Male                0.004655